name: CI/CD
on:
  push:
    branches:
      - develop

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: PHP Lint
        run: find . -name "*.php" -exec php -l {} \;

  build:
    needs: lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Docker Build
        run: docker build -t Luzinho7/job-junia:latest .

  push:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push to Docker Hub
        run: docker push Luzinho7/job-junia:latest
